#
# This file is automatically generated from ripper.y.
# DO NOT MODIFY!!!!!!
#

module RRB
end
require 'rrb_ripper.so'

module RRB
  class Ripper
    def self.parse( s, *args )
      new.parse s, *args
    end

#include handlers
  end
end
