#
# This file is automatically generated from ripper.y.
# DO NOT MODIFY!!!!!!
#

require 'rrb_ripper.so'

class Ripper
  def self.parse( s, *args )
    new.parse s, *args
  end

#include handlers
end
